# .readthedocs.yaml
version: 2

# ✅ 只指定主语言（英文）的 conf.py
sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt