# .readthedocs.yaml
version: 2

# ✅ 正确：使用单数 "sphinx" 和 "configuration"
sphinx:
  configuration: docs/source/conf.py

# 如果你想构建多语言，需要用 "subprojects"
subprojects:
  translations:
    - path: docs/source/zh/conf.py
      language: zh

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements-docs.txt